spacetelescope/stwcs

lib/stwcs/updatewcs/apply_corrections.py
lib/stwcs/updatewcs/wfpc2_dgeo.py
setup.cfg
setup.py

Opus 2015 3dms

---

lib/stwcs/wcsutil/altwcs.py

delete all kw

---

stwcs/wcsutil/altwcs.py

This should finally fix #4 and resolve failing tweakreg test

Catch KeyError when deleting header keywords

---

stwcs/tests/test_hstwcs.py
stwcs/wcsutil/hstwcs.py

fix for refframe=OTHER

---

stwcs/wcsutil/altwcs.py
stwcs/wcsutil/wcscorr.py

Change deprecated `astropy.io.fits` calls.

Change deprecated fits calls

---

stwcs/wcsutil/headerlet.py

fixed more of the fits deprecated calls

Change deprecated calls

---

doc/source/updatewcs.rst
setup.py
stwcs/tests/test_altwcs.py
stwcs/tests/test_astrometrydb.py
stwcs/tests/test_updatewcs.py
stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py

Initial PR to implement new functionality in stwcs to apply headerlets from an astrometry database available through a web-service from MAST.  This implementation includes adding this functionality to the updatewcs function called by the HST calibration pipeline.
This should address all the requirements specified in issue #38 .

Astrometry db v1

---

CHANGES.rst
stwcs/tests/test_headerlet.py
stwcs/wcsutil/headerlet.py

This PR is intended (and based on initial testing will) fix the issue reported in #59 .

Fix sciext problem with restore

---

.gitignore
MANIFEST.in
setup.py

Update RELIC implementation

---

stwcs/updatewcs/utils.py

Minor things that I accidentally noticed.

Minor code clean-up in updatewcs.utils and rewrote diff_angles

---

stwcs/updatewcs/__init__.py

fix bug in cleanWCS

---

.travis.yml
setup.py

Change the Travis matrix and require python >=3.6 in setup.py.

min python version should be 3.6

---

CHANGES.rst
setup.py
stwcs/wcsutil/altwcs.py

~`Fixes #128 and #129.`~
This PR mostly deals with small code improvement in `altwcs` such as making sure `wcskey` is a 1 character space or 'A-Z', converting strings to f-strings and loop optimizations.

Code improvement in AltWCS

---

stwcs/wcsutil/altwcs.py

Fixes a bug introduced in https://github.com/spacetelescope/stwcs/pull/132 (unfortunately). No changelog entry needed (IMO) since the code was not yet released.
CC: @nden

Fix a bug in the AltWCS code

---

stwcs/wcsutil/altwcs.py

Fixes a bug introduced in #132

Fix bug in convertAltWCS - old key modified

---

CHANGES.rst
stwcs/updatewcs/__init__.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/hstwcs.py

This PR extends https://github.com/spacetelescope/stwcs/pull/127 and adds back header comments for `WCSNAMEa` keywords.

Add comment string to WCSNAMEa header keywords

---

stwcs/wcsutil/altwcs.py

Fixes #144 
The bug is due to the change from `'%s' % None` (which worked with `None`) to `f'{fobj.filename():s}'` which crashes when `filename()` is `None` which happens when `fobj` is an in-memory `HDUList`. This bug was introduced in:
https://github.com/spacetelescope/stwcs/pull/132/files#diff-516dcd10bb4c104d97362626d506e981L521-R521

Fix crash due to format conversion bug

---

stwcs/updatewcs/det2im.py
stwcs/updatewcs/npol.py

Fix var number computation in D2IM and CPDIS FITS comment

---

CHANGES.rst
stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py
stwcs/updatewcs/utils.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/hstwcs.py
stwcs/wcsutil/mosaic.py
stwcs/wcsutil/wcscorr.py

This PR is to address https://github.com/spacetelescope/stwcs/pull/147#issuecomment-658369146

Prevent HST-specific WCS keywords from being archived

---

CHANGES.rst
stwcs/wcsutil/headerlet.py

Make headerlet and WCS name comparisons case-insensitive, per https://github.com/spacetelescope/stwcs/issues/146#issuecomment-654871318

Make name checks case-insensitive when applying headerlets

---

README.rst

Replace Travis badge with GA abdge.

add GA badge

---

stwcs/updatewcs/astrometry_utils.py

The new function ``updatewcs.astrometry_utils.build_reference_wcs`` originally only worked with a single file as input.  This prevented it from being used for creating the tangent plane definition for a mosaic or set of dithered observations.  
The simple changes provided here simply allow this function to accept a list of either filenames or HDUList objects as input in addition to a single filename or HDUList.  The docstring was also updated to reflect this change.

Make build_reference_wcs more general

---

.readthedocs.yml

Add RTD configuration with python 3.8+.

Fix for failing RTD jobs

---

.github/workflows/weekly_cron.yml
README.rst
doc/source/fits_convention_tsr/source/sip.rst
doc/source/hstwcs_ui.rst
stwcs/updatewcs/utils.py

Changes to docs, updated readme, updated status badge, renamed weekly cron job

Small changes to docs, readme

---

.github/workflows/ci.yml
CHANGES.rst
stwcs/tests/test_altwcs.py
stwcs/tests/test_astrometrydb.py
stwcs/tests/test_headerlet.py
stwcs/tests/test_updatewcs.py
stwcs/updatewcs/astrometry_utils.py
stwcs/updatewcs/corrections.py
stwcs/updatewcs/det2im.py
stwcs/updatewcs/makewcs.py
stwcs/updatewcs/npol.py
stwcs/wcsutil/instruments.py
stwcs/wcsutil/wcscorr.py

Resolves [HLA-1545](https://jira.stsci.edu/browse/HLA-1545)
Closes #
This PR addresses issues with testing
- enables CI testing on the main branch
- enables some of the astrometry_utils tests
- Removes inheritance from `object` in class definitions
**Checklist for maintainers**
Drizzlepac regression tests pass here:
https://github.com/spacetelescope/RegressionTests/actions/runs/16945074839

HLA-1545: Technical debt

---

CHANGES.rst
doc/source/astrometry_utils.rst
stwcs/distortion/utils.py
stwcs/tests/test_altwcs.py
stwcs/tests/test_astrometrydb.py
stwcs/tests/test_headerlet.py
stwcs/tests/test_updatewcs.py
stwcs/updatewcs/astrometry_utils.py

Resolves [HLA-1541](https://jira.stsci.edu/browse/HLA-1541)
Closes #
This PR addresses an issue with `stwcs.updatewcs.astrometric_utils.find_gsc_offsets` when the response from the GSC service is 500 but the status code is 200.
In addition it improves `make_orthogonal_cd` which often fails in drizzlepac applying headerlets. This issue has at least a couple workarounds in drizzlepac.
Drizzlepac regression tests pass:
https://github.com/spacetelescope/RegressionTests/actions/runs/17077890687
**Checklist for maintainers**

HLA-1541: Issue with GSC webservice returning code 500 and status_code 200 
