spacetelescope/stwcs

.gitignore
lib/stwcs/updatewcs/utils.py

Catch a `KeyError` (not an `AttributeError`) when deleting header keywords. This fixes failing regression tests.

Fix a problem with removing Lookup table distortions.

---

stwcs/wcsutil/altwcs.py
stwcs/wcsutil/headerlet.py

Made changes to ensure that `-SIP` is correctly (not) written to `CTYPE` depending on the use case. Some of these were fixed in astropy and this PR essentially keeps up with changes in `astropy.wcs`.
Supersedes #5.

fix for '-SIP' in ctype

---

stwcs/wcsutil/headerlet.py

The old code would crash with ``KeyError`` if one of the header keywords intended to be deleted was not present in the header.

Fixes a bug (KeyError crash in applying headerlets using ``apply_as_primary``) revealed in Footprints ticket no. 9151

---

stwcs/updatewcs/__init__.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/hstwcs.py

`astropy.wcs` prints a log.info message when `wcs.to_header(relax=False)` is run. The messages informs that "-SIP" was stripped from `CTYPE`. Because `relax=False` means SIP should not be present in the returned header, there should be nothing unexpected in this behaviour. A proposed PR on `astropy` removes this message. 
The message is benign but creates a lot of confusion for drizzlepac users.
This PR catches this particular message so it's not printed when `drizzlepac` runs.

Catch info messages

---

CHANGES.rst
stwcs/updatewcs/__init__.py

astropy/#5065 implements lazy loading of HDUs. This PR fixes some of the broken existing functionality bu reading all HDUs.

update to keep in sync with astropy

---

stwcs/distortion/utils.py

``ignoreHST`` was forgotten in the code from an earlier, experimental version of the ``stwcs.distortion.utils.make_orthogonal_cd()`` function. The logic that uses this variable should be removed.
@stsci-hack Please review the changes.

remove unused ignoreHST variable

---

CHANGES.rst
stwcs/wcsutil/headerlet.py

rename 'clobber' to 'overwrite' in calls to fits.writeto()

---

stwcs/wcsutil/altwcs.py

This PR addresses a Python 3 compatibility issue described in https://github.com/spacetelescope/stwcs/issues/29

Switch from string.uppercase to string.ascii_uppercase

---

CHANGES.rst
stwcs/updatewcs/__init__.py
stwcs/updatewcs/apply_corrections.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/hstwcs.py

This closes #25 #26 but takes a different approach. The warnings are filtered out. It's safe to do this because only one specific warning is filtered out and only in cases when it's not relevant.

suppress warning messages when it's known they are not relevant

---

stwcs/__init__.py

- Prevent unnecessary TEAL-related printing on package import
- Update docstring to refer to `astropy.wcs` instead of `pywcs`

Remove print statement on package import when TEAL tasknames not found

---

.travis.yml

As of Sep 21st `astropy` has dropped support for Python 2.
This PR updates the Travis matrix to not test on Python 2.

remove py 2 from travis

---

stwcs/updatewcs/astrometry_utils.py

This adds logic to guard against the situation when no solutions are returned by the AstrometryDB service for an exposure while also adding log messages reporting that no updates will be applied and why.
This will, based on interactive use of Pandokia testing, resolve the regression test errors (not failures) reported lately in the Drizzlepac nightly regression tests.

Fix Astrometry update with no new WCS

---

stwcs/updatewcs/astrometry_utils.py

The way creation of the string `serviceEndPoint` is implemented is prone to failure when one of the variables cannot be converted to `str`, e.g., when one of them is `None`. This PR attempts to fix this bug. However, it does not fix the underlying issue as to why `solutionID` is `None`???
@stsci-hack

Fix astrometry_db erros due to poor serviceEndPoint string formation

---

stwcs/distortion/utils.py
stwcs/tests/test_headerlet.py
stwcs/tests/test_updatewcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/hstwcs.py
stwcs/wcsutil/mosaic.py

This replaces `wcs._naxis1(2)` with `wcs.pixel_shape` and fits `clobber` with `overwrite`.

Fix Deprecation Warnings

---

.travis.yml
CHANGES.rst
stwcs/tests/test_updatewcs.py
stwcs/updatewcs/__init__.py
stwcs/updatewcs/apply_corrections.py
stwcs/updatewcs/astrometry_utils.py
stwcs/updatewcs/utils.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/hstwcs.py

depends on spacetelescope/stsci.tools#86
This PR supersedes #68 and addresses #67.
It adds supports for HDUList objects as inputs to updatewcs. At the moment the files passed to updatewcs must be opened in `update` mode.

updatewcs should work with HDUList objects

---

CHANGES.rst
stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py

The astrometry database underwent some revision which slightly changed the information which gets returned upon requesting a new WCS for an observation.  This revision, however, caused the original implementation of the results parser to fail.  The changes here look for the new solutions and related information about them from the returned XML in a more general manner avoiding the previous problems with a pre-defined structure which was used in the original implementation.  
The changes here also include a switch of the default server from DEV to TEST, where the TEST server is available publicly, thereby allowing anyone to start getting any available new WCS solutions.

Update XML parsing, update to MASTTEST server

---

stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py

Discussing the original implementation of the astrometry database interface with MAST made it clear that having the ability to write headerlets to the database in the pipeline for new observations, it only caused problems for external users.  Therefore, we are simply removing the ability of 'updatewcs' or  the AstrometryDB class to update the database as it was not deemed worth the trouble (especially with regards to security).  
In addition, MAST finally got the database configured properly on a public server, so we are now able to provide that URL as the default in the software.

Move dB to MAST, remove write to dB methods

---

CHANGES.rst
stwcs/updatewcs/astrometry_utils.py

The astrometry database can (as uncovered in testing) return query results for an image where all fields have a value of 'None', effectively a NULL result with no WCS.  This small set of changes protects against that as gracefully as possible, instead of throwing an Exception that would impede the pipeline when used.

Respond gracefully to null result from database

---

stwcs/updatewcs/astrometry_utils.py

Astrometry database population implemented what will now be a standardized naming convention for both the WCSNAME and HDRNAME keywords for the headerlets.  The 'best' solution provided by the database corresponds to the WCSNAME value, instead of the HDRNAME keyword value which the code originally was written to look for.  
This code change will now recognize the 'best' solution from the database using the WCSNAME (as the database expects) for application to the data as designed.

Select best db solution based on WCSNAME

---

stwcs/updatewcs/astrometry_utils.py

The logic for applying the best WCS solution works perfectly well for pipeline calibration use where no previous solutions from the database have been added as extensions to the exposure yet.  However, upon re-running updatewcs (which people reprocessing their data to align to various catalogs will need to do), the 'best' WCS solution did NOT get applied to avoid adding duplicate extensions with the same WCS solution.
This change splits the logic so that it checks for the presence of each solution from the database, and appends it to the file if it is new THEN after that operation completes, it applies the 'best' solution as the primary WCS using the full list headerlet extensions.  This insures that the solution which gets applied has already been appended as an extension (archived), …

Fix reapply bestwcs

---

CHANGES.rst
stwcs/updatewcs/astrometry_utils.py
stwcs/wcsutil/headerlet.py

This change addresses problems in the headerlet code when replacing one headerlet/WCS with another which uses a different distortion model.

Correct code that archives WCSs with different distortion models

---

CHANGES.rst
stwcs/wcsutil/headerlet.py

Using 'pdb' to track how the 'apply_as_primary()' method worked, it turned out that the WCS keywords from the headerlet were being copied into the science file science extension header using 'header.extend'.  This creates copies of the header keywords at the end of the header resulting in multiple versions of some WCS keywords like the 'wcsname' keyword (for example).  More crucially, it was not allowing new keywords, like 'hdrname', to end up in the output science header.  
This update changes that code to use 'header.update' instead which results in all the new keywords from the headerlet showing up in the science header while also getting the new values from the headerlet into the science header.  
This would address #121 based on interactive tests using 'jc0593z1q'.

Revise apply_as_primary to use update

---

CHANGES.rst
stwcs/updatewcs/astrometry_utils.py
stwcs/wcsutil/headerlet.py

This pull request allows solutions from the astrometry database to be appended to an observation, but if the 'best' solution is identical to the currently active WCS, it does NOT update from the headerlet.  
We have found during extended testing that some of the solutions in the astrometry database are not complete and use of these solutions as an active WCS can cause WCS-related code to thrown an exception.  This simple change not only makes the code more reasonable it what it applies, but further protects pipeline use of the code from throwing an exception in limited use cases.

Add logic to ignore updating header with the same WCS from the database

---

CHANGES.rst
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/mosaic.py
stwcs/wcsutil/wcscorr.py

This PR strips trailing spaces from WCS header keywords before corresponding `astropy.io.fits.Header` cards are created. This should allow using `stwcs` with older versions of `astropy` not containing https://github.com/astropy/astropy/pull/10482 fix.
Closes #125

Do not add trailing spaces to WCS header keywords

---

stwcs/wcsutil/altwcs.py

`tweakreg` in `drizzlepac` started crashing after https://github.com/spacetelescope/stwcs/pull/132 depending on the values of `wcsname` keyword and `reusename`. This is due to the following change:
https://github.com/spacetelescope/stwcs/pull/132/files#diff-516dcd10bb4c104d97362626d506e981L75-L76
and https://github.com/mcara/stwcs/blob/98b2007defc5be07295676fb31d6eb89e61fe1b8/stwcs/wcsutil/altwcs.py#L62-L66
The reason this code was not crashing before was that it could never execute since `wcsname` and `wcskey` could not evaluate to false (default values for these parameters are a blank space `' '`  which does not evaluate to `False`).
This effectively means that the check:
```python
if wcskey == ' ' and wcsname == ' ':
raise KeyError("Either wcskey or wcsname should be specified")
``` …

Fix a crash in tweakreg due to recent code changes

---

.gitignore
CHANGES.rst
stwcs/updatewcs/corrections.py
stwcs/updatewcs/det2im.py
stwcs/updatewcs/npol.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/hstwcs.py

This PR fixes issues with WCS keyword comments disappearing when archiving a WCS. Also, this PR adds new comments to `OCX*`, `OCY*`, `IDC*`, `CD*`, and `SIP` coefficients.

Add and preserve existing WCS comments

---

CHANGES.rst
stwcs/wcsutil/altwcs.py

This PR fixes #82 (increased reliability of detecting alternate WCS in the header), fixes #133, fixes #139, fixes #140 
In addition, it consolidates code that is used in numerous other functions into one single function `_read_alt_wcs()`. This improves code maintenance.

Do not archive non-altwcs specific keywords

---

CHANGES.rst
stwcs/wcsutil/altwcs.py

This PR adds support for backing up, reading, and restoring non-standard WCS keywords created by other ST packages such as `TweakReg`. At this moment the following keywords are:
```
'WCSTYPE', 'RMS_RA', 'RMS_DEC', 'NMATCH', 'FITNAME'
```

Archive and restore non-standard WCS-related keywords

---

stwcs/wcsutil/altwcs.py

This PR fixes two bugs in the `wcs_from_key()` (one carried over from `readAltWCS` and new one:
1. When WCS with provided key does not exist - return an empty header instead of `None`
2. `to_key_s = from_key.strip()` should be `to_key_s = to_key.strip()`

Bug fix in wcs_from_key

---

stwcs/wcsutil/altwcs.py

This PR restores original behavior of `readAltWCS`. It also adds logging of WCSLIB error when loading an Alt WCS

Original readAltWCS was returning None when Alt WCS not found

---

stwcs/wcsutil/altwcs.py

Expands the list of STWCS-specific keywords that need to be archived/restored/deleted by `altwcs` first defined in #135

Add HDRNAME and ORIENTAT to the list of STWCS keywords

---

stwcs/wcsutil/altwcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/wcscorr.py

Several code enhancements:
1. `wcsnames()` and `next_wcskey()` accept `HDUList` of string file name and extension. However, most of the time calling code already performed most checks and repeating checks on input file name and extensions is not needed. `_next_wcskey()` and `_alt_wcs_names()` accept `Header` objects skipping `fobj` and `ext` checks;
2. ~In every case that I saw, having OPUS WCS returned by `wcsnames()` is not desirable. Often a call to `wcsnames()` is followed by deletion of the `'O'` key. `_alt_wcs_names()` removes OPUS WCS before returning `wcskey: name` dictionary.~
3. `wcskeys()` was enhanced to use `'?'` instead of `'*'` as wildcard since WCS keys are 1 character. This makes code more robust.

Performance and reliability improvements

---

CHANGES.rst
stwcs/tests/test_altwcs.py
stwcs/tests/test_updatewcs.py
stwcs/updatewcs/__init__.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/convertwcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/wcscorr.py

This PR adds `archive_wcs()` - an enhanced version of `archiveWCS` with the following additions:
1. Ability to control not only overwriting an Alt WCS **key** (`reusekey` argument in the original `archiveWCS`) but also automatic renaming of the WCS **name** if a WCS with a similar name already exists;
2. Does not allow duplicate **Alt WCS** names (however, primary WCS name may co-exist with a single Alt WCS with the same name);
3. Allows control over what to do in case of conflicts: raise an exception (unless WCS being archived is identical to the conflicting Alt WCS) or quietly quit;
4. WCS names are considered case-insensitive in comparisons, see https://github.com/spacetelescope/stwcs/issues/146.
Closes https://github.com/spacetelescope/stwcs/pull/134
Fixes #130

Add archive_wcs with advanced control and auto-rename

---

stwcs/wcsutil/altwcs.py

Partially undoes https://github.com/spacetelescope/stwcs/pull/154 by removing `'ORIENTAT'` from the list of STWCS-specific keywords. This is due to the fact that length of `'ORIENTAT'` is 8 an adding alternate WCS key results in creation of `'HIERARCH'` cards.

Undo adding ORIENTAT to STWCS-specific keywords

---

CHANGES.rst
doc/source/fits_convention_tsr/source/appendix4.rst
doc/source/npol_tsr/source/npol_append.rst
stwcs/updatewcs/det2im.py
stwcs/updatewcs/npol.py

This PR shortens comment strings for some `D2IM` and `CPDIS` FITS keywords to reduce the number of warning when working with WCSes containing lookup table distortions.
Here is an example of how some comments are currently truncated in FITS headers:
```
D2IM1   = 'AXIS.1: 1' / Axis number of the jth independent variable in a d2im fu
D2IM1   = 'AXIS.2: 2' / Axis number of the jth independent variable in a d2im fu
```
As a result, when running `stwcs.updatewcs.updatewcs()` function on such WCSes produces warnings like these:
```
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
```
This PR solves this issue by removing the word `independent` from the comment for "axis number". This PR also modifies the comment for `CPDIS` to contain the distortion …

Shorten D2IM and CPDIS keyword comments

---

CHANGES.rst
stwcs/tests/test_altwcs.py
stwcs/wcsutil/headerlet.py

When distortion model of the headerlet being applied as primary is different from the current distortion model in the header, the primary WCS should not be archived as loading it back from an alternate WCS would result in incorrect WCS that uses a distortion model not intended for it.
Also, for the same reason, this PR deletes all Alt WCSes before applying a headerlet with a different distortion model.
Fixes #160

Do not archive primary WCS when changing distortion model

---

CHANGES.rst
stwcs/wcsutil/hstwcs.py

`astropy.wcs.WCS.all_world2pix` uses `tolerance` instead of `accuracy` that is used in `stwcs.HSTWCS.all_world2pix` to describe desired accuracy of the results. This PR makes the arguments of both functions compatible (match).

Deprecate "accuracy" in favor of "tolerance" in all_world2pix

---

CHANGES.rst
stwcs/wcsutil/wcscorr.py

This PR fixes a bug due to which `drizzlepac.tweakreg` would crash when trying to align images without OPUS WCS in their header, such as drizzled images.

Fix a bug in wcscorr for images without OPUS WCS

---

CHANGES.rst
stwcs/distortion/utils.py
stwcs/tests/test_altwcs.py
stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py
stwcs/updatewcs/updatehdr.py
stwcs/wcsutil/altwcs.py
stwcs/wcsutil/headerlet.py
stwcs/wcsutil/mosaic.py
stwcs/wcsutil/wcsdiff.py

These changes update the 'updatewcs' task so that when querying the astrometry database, only those WCSs with the same IDCTAB as specified in the image header will be added.  If there are no WCSs in the database because the IDCTAB is new, then it will create a new headerlet based on the new IDCTAB WCS, then compute a new _a priori_ WCS using offsets from the guide star webservice.  
In addition, a new parameter was added to 'updatewcs' to control what WCSs from the database get appended to the file.  By default, only those with the same IDCTAB are added, however, it can be turned on so that ALL WCSs get appended.  
This addresses the issues described in #169.

Compute new apriori WCS 

---

CHANGES.rst
stwcs/updatewcs/__init__.py
stwcs/updatewcs/astrometry_utils.py
stwcs/wcsutil/headerlet.py

These changes fix a problem which was found when appending solutions from the astrometry database as headerlet extensions to images; namely, that there can be duplicate headerlet extensions all with the same `HDRNAME` keyword value.  These problems typically occur as a result of errors in processing, with manual updates to the images being the most prone.  However, the Drizzlepac nightly regression tests process an image which suffers from this problem after updating with all the WCS solutions from the astrometry database (most likely due to multiple entries in the database).
These changes:
- fix a bug in `wcsutil.headerlet.delete_headerlet` to allow multiple extensions to be deleted correctly 
- add a new parameter to the `updatewcs.astrometry_utils.AstrometryDB` method `updateObs()` to …

Remove duplicate headerlet extensions in updatewcs

---

stwcs/updatewcs/updatehdr.py

Simple change to fix an oversight in creating the new updated apriori WCSs to insure that the HDRNAME keyword gets populated correctly.

Fix HDRNAME update

---

stwcs/wcsutil/headerlet.py

This set of changes insures that the IDCTAB, NPOLFILE and D2IMFILE keywords remain in the same part of the primary header as the rest of the calibration reference file keywords.  They reported that these keywords were ending up at the end of the primary header after distortion correction by 'updatewcs', so this PR insures that these keywords do not get moved.

Insure Distortion Keywords Remain in the correct place in the headers

---

CHANGES.rst
stwcs/wcsutil/altwcs.py

A minor bug fix due to which calling `altwcs.archive_wcs()` with `ext='sci'` would cause this function to fail because it was not expanding this extension specification into `[('sci', 1), ('sci', 2), ...]`.
In addition the code for building extension list is slightly more robust.

Allow extensions to be string extname in archive_wcs

---

CHANGES.rst
stwcs/tests/test_hstwcs.py
stwcs/wcsutil/hstwcs.py

This PR improves reliability of the code responsible for computing `extname` property of an `HSTWCS` object when image's primary header contains `'EXTVER'` keyword but is missing `'EXTNAME'`. This will allow `astrodrizzle` to handle such files instead of currently crashing.

Improve handling of primary headers with extver but without extname

---

stwcs/updatewcs/astrometry_utils.py

Recent processing of new HST data triggered an Exception due to not getting any headerlet solutions from the astrometry database of pre-computed corrections.  This simple PR corrects the problem that triggered the Exception by removing a line of code which triggered the Exception yet whose result was never used, and in fact, got recomputed later in the same function. 
This problem originally affected pipeline processing of the single exposure ier510g5q, which was also used to not only reproduce the reported Exception, but also used to confirm that this change correctly fixes this problem with no other apparent side-effects.

Avoid Exception for some new data

---

stwcs/tests/test_updatewcs.py

Fixes failing test when testing against astropy 6.1.0rc1 which contains the bug fix from https://github.com/astropy/astropy/pull/16163 resulting in a small change in computed distortion corrections that affect one unit test.

Fix failing test due to astropy.wcs fix for distortion look-up table bug

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/weekly_cron.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

CHANGES.rst
pyproject.toml

This PR pins numpy to at least numpy 2.0 and updates the changelog for the 1.7.4 planned release tomorrow.

Updated changelog, pin numpy >= 2.0.

---

.github/workflows/ci.yml
.github/workflows/weekly_cron.yml

Resolves [HLA-1443](https://jira.stsci.edu/browse/HLA-1443)
This PR removes regression tests for python 3.10 and adds them for python 3.13. This is done for both the weekly cron job as well as the CI for pull requests.

Added regression testing for python 3.13

---

stwcs/updatewcs/astrometry_utils.py

Resolves [HLA-1467](https://jira.stsci.edu/browse/HLA-1467)
This PR adds a log line at the first check of whether the Astrometry database is available. The line is added right before the check so that it is printed whether the astrometry databased is available or not. 
**Checklist for maintainers**

HLA-1467: Add log info line to astrometry database query
